server:
  port: 8080
  error:
    include-binding-errors: always

springdoc:
  show-actuator: true
  writer-with-default-pretty-printer: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /openapi.yml
        name: v0