apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: __APP_NAME__-hpa
  namespace: __NAMESPACE__
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: __APP_NAME__-deployment
  minReplicas: __MIN_REPLICAS__
  maxReplicas: __MAX_REPLICAS__
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 160
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 160